### ISSUE TITLE
What is the difference between this project and QuickSQL?

### ISSUE THREAD

**Issue by jerryleooo** [Qihoo360/XSQL#4]
I saw there is another project named QuickSQL under Qihoo360, what’s the difference between them?

**Comment by beliefer** [comment]
QuickSQL is different from XSQL. QuickSQL just like a router but XSQL under the calculate engine.

**Comment by jerryleooo** [comment]
You mean QuickSQL has no calculation ability but XSQL has?

**Comment by beliefer** [comment]
Yes. XSQL extends Spark SQL.
