### ISSUE TITLE
When will XSQL support Spark 3.x ?

### ISSUE THREAD

**Issue by dohongdayi** [Qihoo360/XSQL#78]
When will XSQL support Spark 3.x ?

**Comment by WeiWenda** [comment]
It's known that Spark 3.x provide an interface called CatalogPlugin. We have done the same things as XSQL based on CatalogPlugin in another private project. You can learn something from this blog: https://mp.weixin.qq.com/s/mZpvFRwO2xb5j7c5_ZARTQ.

**Comment by dohongdayi** [comment]
So there is no plan to make XSQL support Spark 3.x, because you fully embrace CatalogPlugin and DatasourceV2 within your private project right now ?

**Comment by WeiWenda** [comment]
Sorry, but you can think so.

**Comment by dohongdayi** [comment]
OK, thanks
