### ISSUE TITLE
quicksql未来会停止维护吗？xsql会取代quicksql成为360的异构查询引擎吗？

### ISSUE THREAD

**Issue by liehuoqiangni** [Qihoo360/XSQL#9]

**Comment by beliefer** [comment]
`quicksql` and `XSQL` are responsible for different organizations. I don't know the plan of `quicksql`.
I want to say `XSQL` will continue to update, iterate.

**Comment by liehuoqiangni** [comment]
Thanks a lot.



---原始邮件---
发件人: "Jiaan Geng"<notifications@github.com&gt;
发送时间: 2019年9月10日(星期二) 上午10:28
收件人: "Qihoo360/XSQL"<XSQL@noreply.github.com&gt;;
抄送: "liehuoqiangni"<953174501@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [Qihoo360/XSQL] quicksql未来会停止维护吗？xsql会取代quicksql成为360的异构查询引擎吗？ (#9)



quicksql and XSQL are responsible for different organizations. I don't know the plan of quicksql.
 I want to say XSQL will continue to update, iterate.
